[project]
name = "administrator-de-bloc"
version = "0.1.0"
description = "In this project we create a manager for an entire bloc of flats that takes care of payments and all other important stuff"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
